# Generated by Django 5.0.6 on 2026-08-31 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlaggedSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=255)),
                ('reported_score', models.IntegerField(default=0)),
                ('calculated_score', models.IntegerField(default=0)),
                ('move_count', models.IntegerField(default=0)),
                ('anomaly_type', models.CharField(default='score_mismatch', max_length=50)),
                ('metrics', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='flag_report', to='game.gamesession')),
            ],
        ),
    ]
