# Generated by Django 5.0.6 on 2026-08-31 09:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(blank=True, max_length=50)),
                ('bio', models.TextField(blank=True, max_length=300)),
                ('theme', models.CharField(choices=[('classic_green', 'Nokia 3310 Classic Green LCD (#9bbc0f)'), ('amber_lcd', 'Vintage Amber LCD (#f39c12)'), ('cyan_matrix', 'Cyber Cyan Matrix (#00ffff)'), ('gameboy_olive', 'Retro GameBoy Olive (#8bac0f)'), ('dark_oled', 'Monochrome Dark OLED (#e0e0e0)')], default='classic_green', max_length=30)),
                ('phone_shell', models.CharField(choices=[('classic_navy', 'Nokia 3310 Classic Navy Blue'), ('retro_silver', 'Silver Metallic Edition'), ('ruby_red', 'Ruby Red Passion'), ('stealth_black', 'Stealth Charcoal Black'), ('cyber_yellow', 'Cyberpunk Neon Yellow')], default='classic_navy', max_length=30)),
                ('sound_enabled', models.BooleanField(default=True)),
                ('sound_volume', models.IntegerField(default=80)),
                ('vibration_enabled', models.BooleanField(default=True)),
                ('scanlines_enabled', models.BooleanField(default=True)),
                ('touch_controls_enabled', models.BooleanField(default=True)),
                ('total_games_played', models.PositiveIntegerField(default=0)),
                ('high_score', models.PositiveIntegerField(default=0)),
                ('total_score', models.BigIntegerField(default=0)),
                ('total_apples_eaten', models.PositiveIntegerField(default=0)),
                ('max_snake_length', models.PositiveIntegerField(default=3)),
                ('total_playtime_seconds', models.PositiveIntegerField(default=0)),
                ('xp', models.PositiveIntegerField(default=0)),
                ('rank_level', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-high_score', '-xp'],
            },
        ),
    ]
