# Generated by Django 5.0.6 on 2026-08-31 09:08

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('game', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('emoji', models.CharField(default='🏆', max_length=20)),
                ('mode', models.CharField(choices=[('classic', 'Classic Nokia'), ('time_attack', 'Time Attack (60s)'), ('endless', 'Endless Free-Roam'), ('challenge', 'Labyrinth Challenge')], default='classic', max_length=20)),
                ('difficulty', models.CharField(choices=[('slug', 'Slug (Slow - 140ms)'), ('normal', 'Normal (Standard - 100ms)'), ('python', 'Python (Fast - 70ms)'), ('cobra', 'Cobra (Insane - 45ms)')], default='normal', max_length=20)),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_time', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('prize_title', models.CharField(default='Gold 3310 Champion Trophy', max_length=100)),
                ('prize_xp', models.IntegerField(default=1000)),
            ],
            options={
                'ordering': ['-is_active', 'end_time'],
            },
        ),
        migrations.CreateModel(
            name='TournamentParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('best_score', models.IntegerField(default=0)),
                ('attempts_count', models.IntegerField(default=0)),
                ('last_played_at', models.DateTimeField(auto_now=True)),
                ('best_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.gamesession')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournament_entries', to=settings.AUTH_USER_MODEL)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='tournaments.tournament')),
            ],
            options={
                'ordering': ['-best_score', 'last_played_at'],
                'unique_together': {('tournament', 'player')},
            },
        ),
    ]
