# Generated by Django 5.0.6 on 2026-08-31 09:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameMap',
            fields=[
                ('map_id', models.SlugField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('grid_width', models.IntegerField(default=28)),
                ('grid_height', models.IntegerField(default=16)),
                ('walls_data', models.JSONField(default=list, help_text='List of [x, y] coordinates of solid blocks')),
                ('portals_data', models.JSONField(default=list, help_text='Pairs of [{entry: [x,y], exit: [x,y]}]')),
                ('difficulty_rating', models.IntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mode', models.CharField(choices=[('classic', 'Classic Nokia'), ('time_attack', 'Time Attack (60s)'), ('endless', 'Endless Free-Roam'), ('challenge', 'Labyrinth Challenge')], default='classic', max_length=20)),
                ('difficulty', models.CharField(choices=[('slug', 'Slug (Slow - 140ms)'), ('normal', 'Normal (Standard - 100ms)'), ('python', 'Python (Fast - 70ms)'), ('cobra', 'Cobra (Insane - 45ms)')], default='normal', max_length=20)),
                ('map_name', models.CharField(default='standard_box', max_length=50)),
                ('seed', models.BigIntegerField(help_text='Deterministic PRNG seed for food & powerup spawning')),
                ('client_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('score', models.IntegerField(default=0)),
                ('apples_eaten', models.IntegerField(default=0)),
                ('max_length', models.IntegerField(default=3)),
                ('duration_seconds', models.FloatField(default=0.0)),
                ('move_count', models.IntegerField(default=0)),
                ('death_reason', models.CharField(choices=[('wall', 'Hit Wall'), ('self', 'Ate Self'), ('obstacle', 'Hit Obstacle'), ('timeout', 'Time Expired'), ('quit', 'Surrendered'), ('victory', 'Grid Filled (Max Score)')], default='wall', max_length=20)),
                ('moves_data', models.JSONField(blank=True, default=list)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_flagged', models.BooleanField(default=False)),
                ('flag_reason', models.CharField(blank=True, max_length=255)),
                ('checksum', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='game_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('classic', 'Classic Nokia'), ('time_attack', 'Time Attack (60s)'), ('endless', 'Endless Free-Roam'), ('challenge', 'Labyrinth Challenge')], max_length=20)),
                ('difficulty', models.CharField(choices=[('slug', 'Slug (Slow - 140ms)'), ('normal', 'Normal (Standard - 100ms)'), ('python', 'Python (Fast - 70ms)'), ('cobra', 'Cobra (Insane - 45ms)')], max_length=20)),
                ('score', models.IntegerField(db_index=True)),
                ('apples_eaten', models.IntegerField(default=0)),
                ('max_length', models.IntegerField(default=3)),
                ('duration_seconds', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to=settings.AUTH_USER_MODEL)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recorded_score', to='game.gamesession')),
            ],
            options={
                'ordering': ['-score', 'duration_seconds'],
                'indexes': [models.Index(fields=['mode', '-score'], name='game_score_mode_ac3472_idx'), models.Index(fields=['difficulty', '-score'], name='game_score_difficu_93786f_idx'), models.Index(fields=['created_at', '-score'], name='game_score_created_cec3f0_idx')],
            },
        ),
    ]
